### ISSUE TITLE
Resource model for unbooked sessions

### ISSUE THREAD

**Issue by mecha** [RebelCode/rcmod-wp-bookings-cqrs#4]
Create a SELECT resource model for sessions that only retrieved unbooked sessions.

The query run internally should match something similar to the following:

```
SELECT s.id, s.start, s.end, s.service_id, s.resource_id
FROM sessions as s
LEFT JOIN bookings as b
ON (booking and session collision condition)
WHERE (c) AND (b.id IS NULL);
```

Where `(c)` is the condition given to the `select()` method if the resource model.

**Comment by markzahra** [comment]
I can still reproduce this issue while testing Alpha10.

**Comment by mecha** [comment]
The REST API module was not using this new resource model in EDD Bookings alpha 10. An [issue has been opened](https://github.com/RebelCode/rcmod-eddbk-rest-api/issues/21) in that repo.
